### ISSUE TITLE
GAN

### ISSUE THREAD

**Issue by NethanelK** [deshpandenu/Time-Series-Forecasting-of-Amazon-Stock-Prices-using-Neural-Networks-LSTM-and-GAN-#5]
Hey Nupur,
I'm following your great notebooks  :-) and in notebook five I came across two problems:
1. at the gan_estimator you have a variable that is - tfgan = tf.contrib.gan it works only in TensorFlow version below 1.15, do you have a solution for TensorFlow 2.3 because I could not find one...
2. in the class predict in def gan_predict there is a line - tf.reset_default_graph() that throws an error about nestef graphs but if i remove that line i get an error at this line - predictions = np.array([x for x in gan_estimator.predict(p.gan_predict())])
that there two varibles with the same name 
thank you

**Comment by deshpandenu** [comment]
Hey Nethanel
I got to test this code too...since it's working fine for me but thats also because I preprocessed  my data and didn't add in code in the notebook..
If you can make a gist of the code that isn't testiing right I could have a look at that
If you find a way to get it to work please let me know
I have not worked on this code for a long time but might work on it now
Cheers

**Comment by NethanelK** [comment]
[All_models.py.zip](https://github.com/deshpandenu/Time-Series-Forecasting-of-Amazon-Stock-Prices-using-Neural-Networks-LSTM-and-GAN-/files/5207231/All_models.py.zip)

Thanks for the quick answer
I copied all the notebook to this file (I'm running the code locally)(tf version- 1.14)
and at the gan_estimator.predict(p.gan_predict()) im getting an error pointing to saver.restore(sess, self.gan_model)
the error - tensorflow.python.framework.errors_impl.NotFoundError: Key beta1_power_2 not found in checkpoint
Thanks,
Nethanel
